
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "papyrus.name" . }}-config
  labels:
    {{- include "papyrus.labels" . | nindent 4 }}
data:
  config.json: |-
    {{- if .Values.deployment.configFile }}
    {{- $filePath := printf "config/%s" .Values.deployment.configFile -}}
    {{- if not (.Files.Get $filePath) -}}
    {{- fail (printf "Error: The file %s does not exist in the chart." $filePath) -}}
    {{- else }}
    {{ .Files.Get $filePath | nindent 4 }}
    {{- end }}
    {{- else }}
    {}
    {{- end }}
