{{- if .Values.deployment.configFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "papyrus.name" . }}-config
  labels:
    {{- include "papyrus.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Files.Get (printf "%s" .Values.deployment.configFile) | nindent 4 }}
{{- end }}