{{- if and ( not .Values.backup.enabled ) .Values.p2pService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "papyrus.name" . }}-p2p
  labels:
    {{- include "papyrus.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "papyrus.selectorLabels" . | nindent 6 }}
  type: {{ .Values.p2pService.type }}
  ports:
  - name: p2p
    port: {{ .Values.p2pService.port }}
    protocol: {{ .Values.p2pService.protocol }}
    targetPort: p2p
{{- end }}
